--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 750.0000, height = 1334.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(327)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(375.0000, 667.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1001.0000, height = 1334.0000})
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
Layer:addChild(Panel_1)

--Create scrollView
local scrollView = ccui.ScrollView:create()
scrollView:setBounceEnabled(true)
scrollView:setInnerContainerSize({width = 556, height = 450})
scrollView:ignoreContentAdaptWithSize(false)
scrollView:setClippingEnabled(false)
scrollView:setBackGroundColorOpacity(0)
scrollView:setLayoutComponentEnabled(true)
scrollView:setName("scrollView")
scrollView:setTag(13)
scrollView:setCascadeColorEnabled(true)
scrollView:setCascadeOpacityEnabled(true)
scrollView:setAnchorPoint(0.5000, 0.0000)
scrollView:setPosition(375.0000, 508.0084)
layout = ccui.LayoutComponent:bindLayoutComponent(scrollView)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3808)
layout:setPercentWidth(0.7413)
layout:setPercentHeight(0.3373)
layout:setSize({width = 556.0000, height = 450.0000})
layout:setLeftMargin(97.0000)
layout:setRightMargin(97.0000)
layout:setTopMargin(375.9916)
layout:setBottomMargin(508.0084)
Layer:addChild(scrollView)

--Create btn_ok
local btn_ok = ccui.Button:create()
btn_ok:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTextureNormal("btn-129-79-n.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTexturePressed("btn-129-79-h.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTextureDisabled("btn-129-79-h.png",1)
btn_ok:setTitleFontName("Resource/fonts/OverlapExt.ttf")
btn_ok:setTitleFontSize(36)
btn_ok:setTitleText("OK")
btn_ok:setTitleColor({r = 242, g = 251, b = 254})
btn_ok:setScale9Enabled(true)
btn_ok:setCapInsets({x = 15, y = 11, width = 99, height = 57})
btn_ok:setLayoutComponentEnabled(true)
btn_ok:setName("btn_ok")
btn_ok:setTag(35)
btn_ok:setCascadeColorEnabled(true)
btn_ok:setCascadeOpacityEnabled(true)
btn_ok:setPosition(368.6461, 397.3276)
if callBackProvider~=nil then
      btn_ok:addClickEventListener(callBackProvider("home_lang.lua", btn_ok, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_ok)
layout:setPositionPercentX(0.4915)
layout:setPositionPercentY(0.2978)
layout:setPercentWidth(0.1720)
layout:setPercentHeight(0.0592)
layout:setSize({width = 129.0000, height = 79.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(1)
layout:setLeftMargin(304.1461)
layout:setRightMargin(316.8539)
layout:setTopMargin(897.1724)
layout:setBottomMargin(357.8276)
Layer:addChild(btn_ok)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

