--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-home.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("sp-more-game-ice.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(89)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(0.0000, -1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setSize({width = 588.0000, height = 287.0000})
layout:setLeftMargin(-294.0000)
layout:setRightMargin(-294.0000)
layout:setTopMargin(-142.5000)
layout:setBottomMargin(-144.5000)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Node:addChild(Sprite_1)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-home.plist")
Button_1:loadTextureNormal("sp-more-game-mask.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-home.plist")
Button_1:loadTexturePressed("sp-more-game-mask.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-home.plist")
Button_1:loadTextureDisabled("sp-more-game-mask.png",1)
Button_1:setTitleFontSize(14)
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 573, height = 448})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(91)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(1.0000, -75.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setSize({width = 603.0000, height = 470.0000})
layout:setLeftMargin(-300.5000)
layout:setRightMargin(-302.5000)
layout:setTopMargin(-160.0000)
layout:setBottomMargin(-310.0000)
Node:addChild(Button_1)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(false)
Text_1:setFontSize(16)
Text_1:setString([[  100% India Game,  
非常创新的玩法，你从来也没有见过  
要划出优雅完美的曲线。  
注意，这个游戏非常的硬核]])
Text_1:setTextHorizontalAlignment(1)
Text_1:setTextVerticalAlignment(1)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(92)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(1.0000, -223.5917)
Text_1:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setSize({width = 367.0000, height = 89.0000})
layout:setLeftMargin(-182.5000)
layout:setRightMargin(-184.5000)
layout:setTopMargin(179.0917)
layout:setBottomMargin(-268.0917)
Node:addChild(Text_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

