--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_9
local Panel_9 = ccui.Layout:create()
Panel_9:ignoreContentAdaptWithSize(false)
Panel_9:setClippingEnabled(false)
Panel_9:setBackGroundColorType(1)
Panel_9:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_9:setBackGroundColorOpacity(0)
Panel_9:setTouchEnabled(true);
Panel_9:setLayoutComponentEnabled(true)
Panel_9:setName("Panel_9")
Panel_9:setTag(748)
Panel_9:setCascadeColorEnabled(true)
Panel_9:setCascadeOpacityEnabled(true)
Panel_9:setAnchorPoint(0.5000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_9)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 1080.0000, height = 200.0000})
layout:setLeftMargin(-540.0000)
layout:setRightMargin(-540.0000)
layout:setTopMargin(-200.0000)
Node:addChild(Panel_9)

--Create Sprite_13
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
local Sprite_13 = cc.Sprite:createWithSpriteFrameName("gaming-bm-right.png")
Sprite_13:setName("Sprite_13")
Sprite_13:setTag(749)
Sprite_13:setCascadeColorEnabled(true)
Sprite_13:setCascadeOpacityEnabled(true)
Sprite_13:setAnchorPoint(0.0000, 0.0000)
Sprite_13:setPosition(572.4000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_13)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5300)
layout:setPercentWidth(0.3741)
layout:setPercentHeight(0.6400)
layout:setSize({width = 404.0000, height = 128.0000})
layout:setLeftMargin(572.4000)
layout:setRightMargin(103.6000)
layout:setTopMargin(72.0000)
Sprite_13:setBlendFunc({src = 1, dst = 771})
Panel_9:addChild(Sprite_13)

--Create Button_5
local Button_5 = ccui.Button:create()
Button_5:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
Button_5:loadTextureNormal("tool-find.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
Button_5:loadTexturePressed("tool-find.png",1)
Button_5:loadTextureDisabled("Default/Button_Disable.png",0)
Button_5:setTitleFontSize(14)
Button_5:setTitleColor({r = 65, g = 65, b = 70})
Button_5:setScale9Enabled(true)
Button_5:setCapInsets({x = 15, y = 11, width = 64, height = 82})
Button_5:setLayoutComponentEnabled(true)
Button_5:setName("Button_5")
Button_5:setTag(753)
Button_5:setCascadeColorEnabled(true)
Button_5:setCascadeOpacityEnabled(true)
Button_5:setPosition(74.3071, 63.3403)
Button_5.UserData = {}
Button_5.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      Button_5:addClickEventListener(callBackProvider("gaming_bm.lua", Button_5, "btnFind"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_5)
layout:setPositionPercentX(0.1839)
layout:setPositionPercentY(0.4948)
layout:setPercentWidth(0.2327)
layout:setPercentHeight(0.8125)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(27.3071)
layout:setRightMargin(282.6929)
layout:setTopMargin(12.6597)
layout:setBottomMargin(11.3403)
Sprite_13:addChild(Button_5)

--Create Button_5_0
local Button_5_0 = ccui.Button:create()
Button_5_0:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
Button_5_0:loadTextureNormal("tool-rand.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
Button_5_0:loadTexturePressed("tool-rand.png",1)
Button_5_0:loadTextureDisabled("Default/Button_Disable.png",0)
Button_5_0:setTitleFontSize(14)
Button_5_0:setTitleColor({r = 65, g = 65, b = 70})
Button_5_0:setScale9Enabled(true)
Button_5_0:setCapInsets({x = 15, y = 11, width = 64, height = 82})
Button_5_0:setLayoutComponentEnabled(true)
Button_5_0:setName("Button_5_0")
Button_5_0:setTag(754)
Button_5_0:setCascadeColorEnabled(true)
Button_5_0:setCascadeOpacityEnabled(true)
Button_5_0:setPosition(197.5376, 60.4172)
Button_5_0.UserData = {}
Button_5_0.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      Button_5_0:addClickEventListener(callBackProvider("gaming_bm.lua", Button_5_0, "btnRand"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(Button_5_0)
layout:setPositionPercentX(0.4890)
layout:setPositionPercentY(0.4720)
layout:setPercentWidth(0.2327)
layout:setPercentHeight(0.8125)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(150.5376)
layout:setRightMargin(159.4624)
layout:setTopMargin(15.5828)
layout:setBottomMargin(8.4172)
Sprite_13:addChild(Button_5_0)

--Create btnClear
local btnClear = ccui.Button:create()
btnClear:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnClear:loadTextureNormal("tool-clear.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnClear:loadTexturePressed("tool-clear.png",1)
btnClear:loadTextureDisabled("Default/Button_Disable.png",0)
btnClear:setTitleFontSize(14)
btnClear:setTitleColor({r = 65, g = 65, b = 70})
btnClear:setScale9Enabled(true)
btnClear:setCapInsets({x = 15, y = 11, width = 64, height = 82})
btnClear:setLayoutComponentEnabled(true)
btnClear:setName("btnClear")
btnClear:setTag(755)
btnClear:setCascadeColorEnabled(true)
btnClear:setCascadeOpacityEnabled(true)
btnClear:setPosition(327.8447, 57.4933)
btnClear.UserData = {}
btnClear.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btnClear:addClickEventListener(callBackProvider("gaming_bm.lua", btnClear, "btnClear"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnClear)
layout:setPositionPercentX(0.8115)
layout:setPositionPercentY(0.4492)
layout:setPercentWidth(0.2327)
layout:setPercentHeight(0.8125)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(280.8447)
layout:setRightMargin(29.1553)
layout:setTopMargin(18.5067)
layout:setBottomMargin(5.4933)
Sprite_13:addChild(btnClear)

--Create Sprite_14
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
local Sprite_14 = cc.Sprite:createWithSpriteFrameName("gaming-bm-friend.png")
Sprite_14:setName("Sprite_14")
Sprite_14:setTag(750)
Sprite_14:setCascadeColorEnabled(true)
Sprite_14:setCascadeOpacityEnabled(true)
Sprite_14:setAnchorPoint(1.0000, 0.0000)
Sprite_14:setPosition(507.6000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_14)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.4700)
layout:setPercentWidth(0.3843)
layout:setPercentHeight(0.6000)
layout:setSize({width = 415.0000, height = 120.0000})
layout:setLeftMargin(92.6000)
layout:setRightMargin(572.4000)
layout:setTopMargin(80.0000)
Sprite_14:setBlendFunc({src = 1, dst = 771})
Panel_9:addChild(Sprite_14)

--Create Sprite_15
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
local Sprite_15 = cc.Sprite:createWithSpriteFrameName("animal-1.png")
Sprite_15:setName("Sprite_15")
Sprite_15:setTag(751)
Sprite_15:setCascadeColorEnabled(true)
Sprite_15:setCascadeOpacityEnabled(true)
Sprite_15:setPosition(120.3043, 88.1088)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_15)
layout:setPositionPercentX(0.2899)
layout:setPositionPercentY(0.7342)
layout:setPercentWidth(0.2169)
layout:setPercentHeight(0.9833)
layout:setSize({width = 90.0000, height = 118.0000})
layout:setLeftMargin(75.3043)
layout:setRightMargin(249.6957)
layout:setTopMargin(-27.1088)
layout:setBottomMargin(29.1088)
Sprite_15:setBlendFunc({src = 1, dst = 771})
Sprite_14:addChild(Sprite_15)

--Create Sprite_16
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
local Sprite_16 = cc.Sprite:createWithSpriteFrameName("animal-2.png")
Sprite_16:setName("Sprite_16")
Sprite_16:setTag(752)
Sprite_16:setCascadeColorEnabled(true)
Sprite_16:setCascadeOpacityEnabled(true)
Sprite_16:setPosition(290.1538, 91.6475)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_16)
layout:setPositionPercentX(0.6992)
layout:setPositionPercentY(0.7637)
layout:setPercentWidth(0.2024)
layout:setPercentHeight(0.9167)
layout:setSize({width = 84.0000, height = 110.0000})
layout:setLeftMargin(248.1538)
layout:setRightMargin(82.8462)
layout:setTopMargin(-26.6475)
layout:setBottomMargin(36.6475)
Sprite_16:setBlendFunc({src = 1, dst = 771})
Sprite_14:addChild(Sprite_16)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

