--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_3
local Panel_3 = ccui.Layout:create()
Panel_3:ignoreContentAdaptWithSize(false)
Panel_3:setClippingEnabled(false)
Panel_3:setBackGroundColorType(1)
Panel_3:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_3:setBackGroundColorOpacity(0)
Panel_3:setLayoutComponentEnabled(true)
Panel_3:setName("Panel_3")
Panel_3:setTag(447)
Panel_3:setCascadeColorEnabled(true)
Panel_3:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_3)
layout:setSize({width = 520.0000, height = 420.0000})
layout:setRightMargin(-520.0000)
layout:setTopMargin(-420.0000)
Node:addChild(Panel_3)

--Create Sprite_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local Sprite_2 = cc.Sprite:createWithSpriteFrameName("sp-collection-back.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(448)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(259.6320, 333.7191)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentX(0.4993)
layout:setPositionPercentY(0.7946)
layout:setPercentWidth(0.3481)
layout:setPercentHeight(0.3548)
layout:setSize({width = 181.0000, height = 149.0000})
layout:setLeftMargin(169.1320)
layout:setRightMargin(169.8680)
layout:setTopMargin(11.7809)
layout:setBottomMargin(259.2191)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Panel_3:addChild(Sprite_2)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("")
Text_1:setFontSize(36)
Text_1:setString([[good]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(449)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(265.1655, 222.6959)
Text_1:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.5099)
layout:setPositionPercentY(0.5302)
layout:setPercentWidth(0.1000)
layout:setPercentHeight(0.1000)
layout:setSize({width = 52.0000, height = 42.0000})
layout:setLeftMargin(239.1655)
layout:setRightMargin(228.8345)
layout:setTopMargin(176.3041)
layout:setBottomMargin(201.6959)
Panel_3:addChild(Text_1)

--Create Text_1_0
local Text_1_0 = ccui.Text:create()
Text_1_0:ignoreContentAdaptWithSize(false)
Text_1_0:setFontName("")
Text_1_0:setFontSize(24)
Text_1_0:setString([[info:dkskldjflks lskjdflsk lj sdlkfj sl kw9sljfa9efkj ]])
Text_1_0:setTextHorizontalAlignment(1)
Text_1_0:setTextVerticalAlignment(1)
Text_1_0:setLayoutComponentEnabled(true)
Text_1_0:setName("Text_1_0")
Text_1_0:setTag(450)
Text_1_0:setCascadeColorEnabled(true)
Text_1_0:setCascadeOpacityEnabled(true)
Text_1_0:setPosition(269.1153, 159.2262)
Text_1_0:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1_0)
layout:setPositionPercentX(0.5175)
layout:setPositionPercentY(0.3791)
layout:setPercentWidth(0.6472)
layout:setPercentHeight(0.1820)
layout:setSize({width = 336.5618, height = 76.4262})
layout:setLeftMargin(100.8344)
layout:setRightMargin(82.6038)
layout:setTopMargin(222.5607)
layout:setBottomMargin(121.0131)
Panel_3:addChild(Text_1_0)

--Create Text_1_0_0
local Text_1_0_0 = ccui.Text:create()
Text_1_0_0:ignoreContentAdaptWithSize(true)
Text_1_0_0:setTextAreaSize({width = 0, height = 0})
Text_1_0_0:setFontName("")
Text_1_0_0:setFontSize(24)
Text_1_0_0:setString([[A:how are you ]])
Text_1_0_0:setTextHorizontalAlignment(1)
Text_1_0_0:setTextVerticalAlignment(1)
Text_1_0_0:setLayoutComponentEnabled(true)
Text_1_0_0:setName("Text_1_0_0")
Text_1_0_0:setTag(451)
Text_1_0_0:setCascadeColorEnabled(true)
Text_1_0_0:setCascadeOpacityEnabled(true)
Text_1_0_0:setPosition(236.7430, 103.8261)
Text_1_0_0:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1_0_0)
layout:setPositionPercentX(0.4553)
layout:setPositionPercentY(0.2472)
layout:setPercentWidth(0.2846)
layout:setPercentHeight(0.0667)
layout:setSize({width = 148.0000, height = 28.0000})
layout:setLeftMargin(162.7430)
layout:setRightMargin(209.2570)
layout:setTopMargin(302.1740)
layout:setBottomMargin(89.8261)
Panel_3:addChild(Text_1_0_0)

--Create Text_1_0_0_0
local Text_1_0_0_0 = ccui.Text:create()
Text_1_0_0_0:ignoreContentAdaptWithSize(true)
Text_1_0_0_0:setTextAreaSize({width = 0, height = 0})
Text_1_0_0_0:setFontName("")
Text_1_0_0_0:setFontSize(24)
Text_1_0_0_0:setString([[A:how are you ]])
Text_1_0_0_0:setTextHorizontalAlignment(1)
Text_1_0_0_0:setTextVerticalAlignment(1)
Text_1_0_0_0:setLayoutComponentEnabled(true)
Text_1_0_0_0:setName("Text_1_0_0_0")
Text_1_0_0_0:setTag(453)
Text_1_0_0_0:setCascadeColorEnabled(true)
Text_1_0_0_0:setCascadeOpacityEnabled(true)
Text_1_0_0_0:setPosition(236.6538, 67.5952)
Text_1_0_0_0:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1_0_0_0)
layout:setPositionPercentX(0.4551)
layout:setPositionPercentY(0.1609)
layout:setPercentWidth(0.2846)
layout:setPercentHeight(0.0667)
layout:setSize({width = 148.0000, height = 28.0000})
layout:setLeftMargin(162.6538)
layout:setRightMargin(209.3462)
layout:setTopMargin(338.4048)
layout:setBottomMargin(53.5952)
Panel_3:addChild(Text_1_0_0_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

