--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 750.0000, height = 1334.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(249)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(375.0000, 667.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1001.0000, height = 1334.0000})
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
Layer:addChild(Panel_1)

--Create Panel_1_0
local Panel_1_0 = ccui.Layout:create()
Panel_1_0:ignoreContentAdaptWithSize(false)
Panel_1_0:setClippingEnabled(false)
Panel_1_0:setBackGroundColorType(1)
Panel_1_0:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1_0:setBackGroundColorOpacity(0)
Panel_1_0:setTouchEnabled(true);
Panel_1_0:setLayoutComponentEnabled(true)
Panel_1_0:setName("Panel_1_0")
Panel_1_0:setTag(251)
Panel_1_0:setCascadeColorEnabled(true)
Panel_1_0:setCascadeOpacityEnabled(true)
Panel_1_0:setAnchorPoint(0.5000, 0.5000)
Panel_1_0:setPosition(384.9750, 656.9950)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1_0)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5133)
layout:setPositionPercentY(0.4925)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1001.0000, height = 1334.0000})
layout:setLeftMargin(-115.5250)
layout:setRightMargin(-135.4750)
layout:setTopMargin(10.0050)
layout:setBottomMargin(-10.0050)
Layer:addChild(Panel_1_0)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
Image_1:loadTexture("common-dialog.png",1)
Image_1:setScale9Enabled(true)
Image_1:setCapInsets({x = 219, y = 129, width = 226, height = 135})
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(248)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(500.5000, 667.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6633)
layout:setPercentHeight(0.5202)
layout:setSize({width = 664.0000, height = 694.0000})
layout:setLeftMargin(168.5000)
layout:setRightMargin(168.5000)
layout:setTopMargin(320.0000)
layout:setBottomMargin(320.0000)
Panel_1_0:addChild(Image_1)

--Create btn_ok
local btn_ok = ccui.Button:create()
btn_ok:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTextureNormal("btn-146-92-n.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTexturePressed("btn-146-92-h.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTextureDisabled("btn-146-92-h.png",1)
btn_ok:setTitleFontName("Resource/fonts/OverlapExt.ttf")
btn_ok:setTitleFontSize(48)
btn_ok:setTitleText("OK")
btn_ok:setTitleColor({r = 242, g = 251, b = 254})
btn_ok:setScale9Enabled(true)
btn_ok:setCapInsets({x = 15, y = 11, width = 116, height = 70})
btn_ok:setLayoutComponentEnabled(true)
btn_ok:setName("btn_ok")
btn_ok:setTag(250)
btn_ok:setCascadeColorEnabled(true)
btn_ok:setCascadeOpacityEnabled(true)
btn_ok:setPosition(493.5629, 418.3531)
if callBackProvider~=nil then
      btn_ok:addClickEventListener(callBackProvider("collection_info.lua", btn_ok, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_ok)
layout:setPositionPercentX(0.4931)
layout:setPositionPercentY(0.3136)
layout:setPercentWidth(0.1459)
layout:setPercentHeight(0.0690)
layout:setSize({width = 146.0000, height = 92.0000})
layout:setLeftMargin(420.5629)
layout:setRightMargin(434.4371)
layout:setTopMargin(869.6469)
layout:setBottomMargin(372.3531)
Panel_1_0:addChild(btn_ok)

--Create Panel_2
local Panel_2 = ccui.Layout:create()
Panel_2:ignoreContentAdaptWithSize(false)
Panel_2:setClippingEnabled(false)
Panel_2:setBackGroundColorType(1)
Panel_2:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_2:setBackGroundColorOpacity(0)
Panel_2:setTouchEnabled(true);
Panel_2:setLayoutComponentEnabled(true)
Panel_2:setName("Panel_2")
Panel_2:setTag(7)
Panel_2:setCascadeColorEnabled(true)
Panel_2:setCascadeOpacityEnabled(true)
Panel_2:setPosition(359.4297, 667.9669)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
layout:setPositionPercentX(0.3591)
layout:setPositionPercentY(0.5007)
layout:setPercentWidth(0.2997)
layout:setPercentHeight(0.2249)
layout:setSize({width = 300.0000, height = 300.0000})
layout:setLeftMargin(359.4297)
layout:setRightMargin(341.5703)
layout:setTopMargin(366.0331)
layout:setBottomMargin(667.9669)
Panel_1_0:addChild(Panel_2)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("Resource/fonts/OverlapExt.ttf")
Text_1:setFontSize(48)
Text_1:setString([[totaato]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(8)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(141.2072, 65.4019)
Text_1:setTextColor({r = 15, g = 22, b = 22})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.4707)
layout:setPositionPercentY(0.2180)
layout:setPercentWidth(0.5733)
layout:setPercentHeight(0.1867)
layout:setSize({width = 172.0000, height = 56.0000})
layout:setLeftMargin(55.2072)
layout:setRightMargin(72.7928)
layout:setTopMargin(206.5981)
layout:setBottomMargin(37.4019)
Panel_2:addChild(Text_1)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-home.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("collection-detail-1.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(6)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(152.6024, 202.5788)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentX(0.5087)
layout:setPositionPercentY(0.6753)
layout:setPercentWidth(0.5367)
layout:setPercentHeight(0.5767)
layout:setSize({width = 161.0000, height = 173.0000})
layout:setLeftMargin(72.1024)
layout:setRightMargin(66.8976)
layout:setTopMargin(10.9212)
layout:setBottomMargin(116.0788)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Panel_2:addChild(Sprite_1)

--Create Text_2
local Text_2 = ccui.Text:create()
Text_2:ignoreContentAdaptWithSize(false)
Text_2:setFontName("Resource/fonts/OverlapExt.ttf")
Text_2:setFontSize(20)
Text_2:setString([[it seems someone left behind,not clean,it smells strange.]])
Text_2:setTextHorizontalAlignment(1)
Text_2:setTextVerticalAlignment(1)
Text_2:setLayoutComponentEnabled(true)
Text_2:setName("Text_2")
Text_2:setTag(10)
Text_2:setCascadeColorEnabled(true)
Text_2:setCascadeOpacityEnabled(true)
Text_2:setPosition(494.6046, 630.5299)
Text_2:setTextColor({r = 15, g = 22, b = 22})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_2)
layout:setPositionPercentX(0.4941)
layout:setPositionPercentY(0.4727)
layout:setPercentWidth(0.4022)
layout:setPercentHeight(0.0473)
layout:setSize({width = 402.6020, height = 63.1227})
layout:setLeftMargin(293.3036)
layout:setRightMargin(305.0944)
layout:setTopMargin(671.9088)
layout:setBottomMargin(598.9686)
Panel_1_0:addChild(Text_2)

--Create Sprite_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-home.plist")
local Sprite_2 = cc.Sprite:createWithSpriteFrameName("split-collection-info.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(9)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(495.9028, 590.1574)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentX(0.4954)
layout:setPositionPercentY(0.4424)
layout:setPercentWidth(0.4595)
layout:setPercentHeight(0.0022)
layout:setSize({width = 460.0000, height = 3.0000})
layout:setLeftMargin(265.9028)
layout:setRightMargin(275.0972)
layout:setTopMargin(742.3426)
layout:setBottomMargin(588.6574)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Panel_1_0:addChild(Sprite_2)

--Create Text_2_0
local Text_2_0 = ccui.Text:create()
Text_2_0:ignoreContentAdaptWithSize(false)
Text_2_0:setFontName("Resource/fonts/OverlapExt.ttf")
Text_2_0:setFontSize(20)
Text_2_0:setString([[ccokkect 100 items to unlock]])
Text_2_0:setTextHorizontalAlignment(1)
Text_2_0:setTextVerticalAlignment(1)
Text_2_0:setLayoutComponentEnabled(true)
Text_2_0:setName("Text_2_0")
Text_2_0:setTag(11)
Text_2_0:setCascadeColorEnabled(true)
Text_2_0:setCascadeOpacityEnabled(true)
Text_2_0:setPosition(500.0028, 542.2896)
Text_2_0:setTextColor({r = 72, g = 154, b = 132})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_2_0)
layout:setPositionPercentX(0.4995)
layout:setPositionPercentY(0.4065)
layout:setPercentWidth(0.4022)
layout:setPercentHeight(0.0473)
layout:setSize({width = 402.6020, height = 63.1227})
layout:setLeftMargin(298.7018)
layout:setRightMargin(299.6962)
layout:setTopMargin(760.1491)
layout:setBottomMargin(510.7282)
Panel_1_0:addChild(Text_2_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

