--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(38)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(82.5000, 82.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setSize({width = 165.0000, height = 165.0000})
layout:setRightMargin(-165.0000)
layout:setTopMargin(-165.0000)
Node:addChild(panel)

--Create btn_select
local btn_select = ccui.Button:create()
btn_select:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
btn_select:loadTextureNormal("sp-select-level-board.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
btn_select:loadTexturePressed("sp-select-level-board.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
btn_select:loadTextureDisabled("sp-select-level-board.png",1)
btn_select:setTitleFontSize(14)
btn_select:setTitleColor({r = 65, g = 65, b = 70})
btn_select:setScale9Enabled(true)
btn_select:setCapInsets({x = 15, y = 11, width = 121, height = 101})
btn_select:setLayoutComponentEnabled(true)
btn_select:setName("btn_select")
btn_select:setTag(141)
btn_select:setCascadeColorEnabled(true)
btn_select:setCascadeOpacityEnabled(true)
btn_select:setPosition(80.6354, 84.1676)
if callBackProvider~=nil then
      btn_select:addTouchEventListener(callBackProvider("select_level.lua", btn_select, "onTouch"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_select)
layout:setPositionPercentX(0.4887)
layout:setPositionPercentY(0.5101)
layout:setPercentWidth(0.9152)
layout:setPercentHeight(0.7455)
layout:setSize({width = 151.0000, height = 123.0000})
layout:setLeftMargin(5.1354)
layout:setRightMargin(8.8646)
layout:setTopMargin(19.3324)
layout:setBottomMargin(22.6676)
panel:addChild(btn_select)

--Create Sprite_3
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
local Sprite_3 = cc.Sprite:createWithSpriteFrameName("icon-select-star.png")
Sprite_3:setName("Sprite_3")
Sprite_3:setTag(42)
Sprite_3:setCascadeColorEnabled(true)
Sprite_3:setCascadeOpacityEnabled(true)
Sprite_3:setPosition(62.6590, 40.0229)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_3)
layout:setPositionPercentX(0.3798)
layout:setPositionPercentY(0.2426)
layout:setPercentWidth(0.1636)
layout:setPercentHeight(0.1636)
layout:setSize({width = 27.0000, height = 27.0000})
layout:setLeftMargin(49.1590)
layout:setRightMargin(88.8410)
layout:setTopMargin(111.4771)
layout:setBottomMargin(26.5229)
Sprite_3:setBlendFunc({src = 1, dst = 771})
panel:addChild(Sprite_3)

--Create Sprite_4
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
local Sprite_4 = cc.Sprite:createWithSpriteFrameName("icon-select-star.png")
Sprite_4:setName("Sprite_4")
Sprite_4:setTag(43)
Sprite_4:setCascadeColorEnabled(true)
Sprite_4:setCascadeOpacityEnabled(true)
Sprite_4:setPosition(94.0581, 40.0229)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_4)
layout:setPositionPercentX(0.5700)
layout:setPositionPercentY(0.2426)
layout:setPercentWidth(0.1636)
layout:setPercentHeight(0.1636)
layout:setSize({width = 27.0000, height = 27.0000})
layout:setLeftMargin(80.5581)
layout:setRightMargin(57.4419)
layout:setTopMargin(111.4771)
layout:setBottomMargin(26.5229)
Sprite_4:setBlendFunc({src = 1, dst = 771})
panel:addChild(Sprite_4)

--Create Sprite_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
local Sprite_2 = cc.Sprite:createWithSpriteFrameName("icon-select-star.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(41)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(125.4572, 40.0229)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentX(0.7603)
layout:setPositionPercentY(0.2426)
layout:setPercentWidth(0.1636)
layout:setPercentHeight(0.1636)
layout:setSize({width = 27.0000, height = 27.0000})
layout:setLeftMargin(111.9572)
layout:setRightMargin(26.0428)
layout:setTopMargin(111.4771)
layout:setBottomMargin(26.5229)
Sprite_2:setBlendFunc({src = 1, dst = 771})
panel:addChild(Sprite_2)

--Create level
local level = ccui.Text:create()
level:ignoreContentAdaptWithSize(true)
level:setTextAreaSize({width = 0, height = 0})
level:setFontName("Resource/fonts/OverlapExt.ttf")
level:setFontSize(48)
level:setString([[3-1]])
level:setTextHorizontalAlignment(1)
level:setTextVerticalAlignment(1)
level:setLayoutComponentEnabled(true)
level:setName("level")
level:setTag(44)
level:setCascadeColorEnabled(true)
level:setCascadeOpacityEnabled(true)
level:setPosition(71.1918, 99.7971)
level:setTextColor({r = 15, g = 22, b = 22})
layout = ccui.LayoutComponent:bindLayoutComponent(level)
layout:setPositionPercentX(0.4315)
layout:setPositionPercentY(0.6048)
layout:setPercentWidth(0.4909)
layout:setPercentHeight(0.3394)
layout:setSize({width = 81.0000, height = 56.0000})
layout:setLeftMargin(30.6918)
layout:setRightMargin(53.3082)
layout:setTopMargin(37.2029)
layout:setBottomMargin(71.7971)
panel:addChild(level)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

