--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create head
local head=cc.Node:create()
head:setName("head")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(83)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 300.0000, height = 300.0000})
layout:setLeftMargin(-150.0000)
layout:setRightMargin(-150.0000)
layout:setTopMargin(-150.0000)
layout:setBottomMargin(-150.0000)
head:addChild(Panel_1)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("head-circle-in.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(84)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(150.0000, 150.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6400)
layout:setPercentHeight(0.6433)
layout:setSize({width = 192.0000, height = 193.0000})
layout:setLeftMargin(54.0000)
layout:setRightMargin(54.0000)
layout:setTopMargin(53.5000)
layout:setBottomMargin(53.5000)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Panel_1:addChild(Sprite_1)

--Create Sprite_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
local Sprite_2 = cc.Sprite:createWithSpriteFrameName("head-kitty.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(85)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(150.0000, 137.1033)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4570)
layout:setPercentWidth(0.5667)
layout:setPercentHeight(0.5333)
layout:setSize({width = 170.0000, height = 160.0000})
layout:setLeftMargin(65.0000)
layout:setRightMargin(65.0000)
layout:setTopMargin(82.8967)
layout:setBottomMargin(57.1033)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Panel_1:addChild(Sprite_2)

--Create Sprite_3
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
local Sprite_3 = cc.Sprite:createWithSpriteFrameName("head-circle-out.png")
Sprite_3:setName("Sprite_3")
Sprite_3:setTag(86)
Sprite_3:setCascadeColorEnabled(true)
Sprite_3:setCascadeOpacityEnabled(true)
Sprite_3:setPosition(150.0000, 150.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_3)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6900)
layout:setPercentHeight(0.7200)
layout:setSize({width = 207.0000, height = 216.0000})
layout:setLeftMargin(46.5000)
layout:setRightMargin(46.5000)
layout:setTopMargin(42.0000)
layout:setBottomMargin(42.0000)
Sprite_3:setBlendFunc({src = 1, dst = 771})
Panel_1:addChild(Sprite_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = head
return result;
end

return Result

