--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 750.0000, height = 1334.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(282)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(375.0000, 667.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1001.0000, height = 1334.0000})
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
Layer:addChild(Panel_1)

--Create pageView
local pageView = ccui.PageView:create()
pageView:ignoreContentAdaptWithSize(false)
pageView:setClippingEnabled(false)
pageView:setBackGroundColorType(1)
pageView:setBackGroundColor({r = 150, g = 150, b = 100})
pageView:setBackGroundColorOpacity(0)
pageView:setLayoutComponentEnabled(true)
pageView:setName("pageView")
pageView:setTag(35)
pageView:setCascadeColorEnabled(true)
pageView:setCascadeOpacityEnabled(true)
pageView:setAnchorPoint(0.5000, 0.5000)
pageView:setPosition(375.0000, 667.0000)
if callBackProvider~=nil then
      pageView:addEventListener(callBackProvider("olap_travel.lua", pageView, "onEvent"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(pageView)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1001.0000, height = 1334.0000})
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
Layer:addChild(pageView)

--Create btn_right
local btn_right = ccui.Button:create()
btn_right:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
btn_right:loadTextureNormal("btn-select-scene-right-n.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
btn_right:loadTexturePressed("btn-select-scene-right-n.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
btn_right:loadTextureDisabled("btn-select-scene-right-n.png",1)
btn_right:setTitleFontSize(14)
btn_right:setTitleColor({r = 65, g = 65, b = 70})
btn_right:setScale9Enabled(true)
btn_right:setCapInsets({x = 15, y = 11, width = 8, height = 45})
btn_right:setLayoutComponentEnabled(true)
btn_right:setName("btn_right")
btn_right:setTag(84)
btn_right:setCascadeColorEnabled(true)
btn_right:setCascadeOpacityEnabled(true)
btn_right:setPosition(714.0000, 667.0000)
if callBackProvider~=nil then
      btn_right:addClickEventListener(callBackProvider("olap_travel.lua", btn_right, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_right)
layout:setPositionPercentX(0.9520)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.0507)
layout:setPercentHeight(0.0502)
layout:setSize({width = 38.0000, height = 67.0000})
layout:setHorizontalEdge(2)
layout:setLeftMargin(695.0000)
layout:setRightMargin(17.0000)
layout:setTopMargin(633.5000)
layout:setBottomMargin(633.5000)
Layer:addChild(btn_right)

--Create btn_left
local btn_left = ccui.Button:create()
btn_left:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
btn_left:loadTextureNormal("btn-select-scene-left-n.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
btn_left:loadTexturePressed("btn-select-scene-left-n.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
btn_left:loadTextureDisabled("btn-select-scene-left-n.png",1)
btn_left:setTitleFontSize(14)
btn_left:setTitleColor({r = 65, g = 65, b = 70})
btn_left:setScale9Enabled(true)
btn_left:setCapInsets({x = 15, y = 11, width = 8, height = 45})
btn_left:setLayoutComponentEnabled(true)
btn_left:setName("btn_left")
btn_left:setTag(85)
btn_left:setCascadeColorEnabled(true)
btn_left:setCascadeOpacityEnabled(true)
btn_left:setPosition(36.0000, 667.0000)
if callBackProvider~=nil then
      btn_left:addClickEventListener(callBackProvider("olap_travel.lua", btn_left, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_left)
layout:setPositionPercentX(0.0480)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.0507)
layout:setPercentHeight(0.0502)
layout:setSize({width = 38.0000, height = 67.0000})
layout:setHorizontalEdge(1)
layout:setLeftMargin(17.0000)
layout:setRightMargin(695.0000)
layout:setTopMargin(633.5000)
layout:setBottomMargin(633.5000)
Layer:addChild(btn_left)

--Create btn_back
local btn_back = ccui.Button:create()
btn_back:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_back:loadTextureNormal("btn-129-79-n.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_back:loadTexturePressed("btn-129-79-h.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_back:loadTextureDisabled("btn-129-79-h.png",1)
btn_back:setTitleFontSize(14)
btn_back:setTitleColor({r = 65, g = 65, b = 70})
btn_back:setScale9Enabled(true)
btn_back:setCapInsets({x = 15, y = 11, width = 99, height = 57})
btn_back:setLayoutComponentEnabled(true)
btn_back:setName("btn_back")
btn_back:setTag(86)
btn_back:setCascadeColorEnabled(true)
btn_back:setCascadeOpacityEnabled(true)
btn_back:setPosition(81.5000, 113.6212)
if callBackProvider~=nil then
      btn_back:addClickEventListener(callBackProvider("olap_travel.lua", btn_back, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_back)
layout:setPositionPercentX(0.1087)
layout:setPositionPercentY(0.0852)
layout:setPercentWidth(0.1720)
layout:setPercentHeight(0.0592)
layout:setSize({width = 129.0000, height = 79.0000})
layout:setHorizontalEdge(1)
layout:setLeftMargin(17.0000)
layout:setRightMargin(604.0000)
layout:setTopMargin(1180.8790)
layout:setBottomMargin(74.1212)
Layer:addChild(btn_back)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("label-btn-common-back.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(87)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(64.5000, 39.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2713)
layout:setPercentHeight(0.4430)
layout:setSize({width = 35.0000, height = 35.0000})
layout:setLeftMargin(47.0000)
layout:setRightMargin(47.0000)
layout:setTopMargin(22.0000)
layout:setBottomMargin(22.0000)
Sprite_1:setBlendFunc({src = 1, dst = 771})
btn_back:addChild(Sprite_1)

--Create Sprite_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
local Sprite_2 = cc.Sprite:createWithSpriteFrameName("slider-select-travel.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(160)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(374.9642, 1205.9030)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9040)
layout:setPercentWidth(0.7627)
layout:setPercentHeight(0.0172)
layout:setSize({width = 572.0000, height = 23.0000})
layout:setLeftMargin(88.9642)
layout:setRightMargin(89.0358)
layout:setTopMargin(116.5969)
layout:setBottomMargin(1194.4030)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Sprite_2)

--Create Sprite_3_0
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
local Sprite_3_0 = cc.Sprite:createWithSpriteFrameName("icon-select-percent-red.png")
Sprite_3_0:setName("Sprite_3_0")
Sprite_3_0:setTag(161)
Sprite_3_0:setCascadeColorEnabled(true)
Sprite_3_0:setCascadeOpacityEnabled(true)
Sprite_3_0:setPosition(558.7348, 11.5496)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_3_0)
layout:setPositionPercentX(0.9768)
layout:setPositionPercentY(0.5022)
layout:setPercentWidth(0.0210)
layout:setPercentHeight(1.0000)
layout:setSize({width = 12.0000, height = 23.0000})
layout:setLeftMargin(552.7348)
layout:setRightMargin(7.2652)
layout:setTopMargin(-0.0496)
layout:setBottomMargin(0.0496)
Sprite_3_0:setBlendFunc({src = 1, dst = 771})
Sprite_2:addChild(Sprite_3_0)

--Create Panel_3
local Panel_3 = ccui.Layout:create()
Panel_3:ignoreContentAdaptWithSize(false)
Panel_3:setClippingEnabled(false)
Panel_3:setBackGroundColorType(1)
Panel_3:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_3:setBackGroundColorOpacity(0)
Panel_3:setLayoutComponentEnabled(true)
Panel_3:setName("Panel_3")
Panel_3:setTag(162)
Panel_3:setCascadeColorEnabled(true)
Panel_3:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_3)
layout:setPercentWidth(0.3497)
layout:setPercentHeight(8.6957)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setRightMargin(372.0000)
layout:setTopMargin(-177.0000)
Sprite_2:addChild(Panel_3)

--Create Sprite_3
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
local Sprite_3 = cc.Sprite:createWithSpriteFrameName("icon-select-percent-green.png")
Sprite_3:setName("Sprite_3")
Sprite_3:setTag(163)
Sprite_3:setCascadeColorEnabled(true)
Sprite_3:setCascadeOpacityEnabled(true)
Sprite_3:setPosition(103.7066, 11.3902)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_3)
layout:setPositionPercentX(0.5185)
layout:setPositionPercentY(0.0570)
layout:setPercentWidth(0.0550)
layout:setPercentHeight(0.1000)
layout:setSize({width = 11.0000, height = 20.0000})
layout:setLeftMargin(98.2066)
layout:setRightMargin(90.7934)
layout:setTopMargin(178.6098)
layout:setBottomMargin(1.3902)
Sprite_3:setBlendFunc({src = 1, dst = 771})
Panel_3:addChild(Sprite_3)

--Create Sprite_5
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-select.plist")
local Sprite_5 = cc.Sprite:createWithSpriteFrameName("icon-select-percent-arrow.png")
Sprite_5:setName("Sprite_5")
Sprite_5:setTag(164)
Sprite_5:setCascadeColorEnabled(true)
Sprite_5:setCascadeOpacityEnabled(true)
Sprite_5:setPosition(102.8866, 37.0068)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_5)
layout:setPositionPercentX(0.5144)
layout:setPositionPercentY(0.1850)
layout:setPercentWidth(0.2250)
layout:setPercentHeight(0.1150)
layout:setSize({width = 45.0000, height = 23.0000})
layout:setLeftMargin(80.3866)
layout:setRightMargin(74.6134)
layout:setTopMargin(151.4932)
layout:setBottomMargin(25.5068)
Sprite_5:setBlendFunc({src = 1, dst = 771})
Panel_3:addChild(Sprite_5)

--Create Text_1_0
local Text_1_0 = ccui.Text:create()
Text_1_0:ignoreContentAdaptWithSize(true)
Text_1_0:setTextAreaSize({width = 0, height = 0})
Text_1_0:setFontName("Resource/fonts/OverlapExt.ttf")
Text_1_0:setFontSize(20)
Text_1_0:setString([[you:13]])
Text_1_0:setLayoutComponentEnabled(true)
Text_1_0:setName("Text_1_0")
Text_1_0:setTag(166)
Text_1_0:setCascadeColorEnabled(true)
Text_1_0:setCascadeOpacityEnabled(true)
Text_1_0:setPosition(108.9496, -20.0323)
Text_1_0:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1_0)
layout:setPositionPercentX(0.5447)
layout:setPositionPercentY(-0.1002)
layout:setPercentWidth(0.3050)
layout:setPercentHeight(0.1150)
layout:setSize({width = 61.0000, height = 23.0000})
layout:setLeftMargin(78.4496)
layout:setRightMargin(60.5504)
layout:setTopMargin(208.5323)
layout:setBottomMargin(-31.5323)
Panel_3:addChild(Text_1_0)

--Create Text_1_0_0
local Text_1_0_0 = ccui.Text:create()
Text_1_0_0:ignoreContentAdaptWithSize(true)
Text_1_0_0:setTextAreaSize({width = 0, height = 0})
Text_1_0_0:setFontName("Resource/fonts/OverlapExt.ttf")
Text_1_0_0:setFontSize(20)
Text_1_0_0:setString([[max:133]])
Text_1_0_0:setLayoutComponentEnabled(true)
Text_1_0_0:setName("Text_1_0_0")
Text_1_0_0:setTag(192)
Text_1_0_0:setCascadeColorEnabled(true)
Text_1_0_0:setCascadeOpacityEnabled(true)
Text_1_0_0:setPosition(542.2318, 40.3083)
Text_1_0_0:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1_0_0)
layout:setPositionPercentX(2.7112)
layout:setPositionPercentY(0.2015)
layout:setPercentWidth(0.3800)
layout:setPercentHeight(0.1150)
layout:setSize({width = 76.0000, height = 23.0000})
layout:setLeftMargin(504.2318)
layout:setRightMargin(-380.2318)
layout:setTopMargin(148.1917)
layout:setBottomMargin(28.8083)
Panel_3:addChild(Text_1_0_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

