--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create mainTop
local mainTop=cc.Node:create()
mainTop:setName("mainTop")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 255, g = 166, b = 195})
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(80)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 1080.0000, height = 150.0000})
layout:setLeftMargin(-540.0000)
layout:setRightMargin(-540.0000)
layout:setBottomMargin(-150.0000)
mainTop:addChild(Panel_1)

--Create btnActivity
local btnActivity = ccui.Button:create()
btnActivity:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnActivity:loadTextureNormal("main-top-activity.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnActivity:loadTexturePressed("main-top-activity.png",1)
btnActivity:loadTextureDisabled("Default/Button_Disable.png",0)
btnActivity:setTitleFontSize(14)
btnActivity:setTitleColor({r = 65, g = 65, b = 70})
btnActivity:setScale9Enabled(true)
btnActivity:setCapInsets({x = 15, y = 11, width = 120, height = 134})
btnActivity:setLayoutComponentEnabled(true)
btnActivity:setName("btnActivity")
btnActivity:setTag(96)
btnActivity:setCascadeColorEnabled(true)
btnActivity:setCascadeOpacityEnabled(true)
btnActivity:setPosition(209.6205, -346.2184)
btnActivity.UserData = {}
btnActivity.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btnActivity:addClickEventListener(callBackProvider("main_top.lua", btnActivity, "btnActivity"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnActivity)
layout:setPositionPercentX(0.1941)
layout:setPositionPercentY(-2.3081)
layout:setPercentWidth(0.1389)
layout:setPercentHeight(1.0400)
layout:setSize({width = 150.0000, height = 156.0000})
layout:setLeftMargin(134.6205)
layout:setRightMargin(795.3795)
layout:setTopMargin(418.2184)
layout:setBottomMargin(-424.2184)
Panel_1:addChild(btnActivity)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("main-top-head.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(81)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(541.4040, -35.6400)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5013)
layout:setPositionPercentY(-0.2376)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.7333)
layout:setSize({width = 1080.0000, height = 110.0000})
layout:setLeftMargin(1.4040)
layout:setRightMargin(-1.4041)
layout:setTopMargin(130.6400)
layout:setBottomMargin(-90.6400)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Panel_1:addChild(Sprite_1)

--Create btnFriend
local btnFriend = ccui.Button:create()
btnFriend:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnFriend:loadTextureNormal("main-top-friend.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnFriend:loadTexturePressed("main-top-friend.png",1)
btnFriend:loadTextureDisabled("Default/Button_Disable.png",0)
btnFriend:setTitleFontSize(14)
btnFriend:setTitleColor({r = 65, g = 65, b = 70})
btnFriend:setScale9Enabled(true)
btnFriend:setCapInsets({x = 15, y = 11, width = 120, height = 163})
btnFriend:setLayoutComponentEnabled(true)
btnFriend:setName("btnFriend")
btnFriend:setTag(95)
btnFriend:setCascadeColorEnabled(true)
btnFriend:setCascadeOpacityEnabled(true)
btnFriend:setPosition(206.7092, -165.7110)
btnFriend.UserData = {}
btnFriend.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btnFriend:addClickEventListener(callBackProvider("main_top.lua", btnFriend, "btnFriend"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnFriend)
layout:setPositionPercentX(0.1914)
layout:setPositionPercentY(-1.1047)
layout:setPercentWidth(0.1389)
layout:setPercentHeight(1.2333)
layout:setSize({width = 150.0000, height = 185.0000})
layout:setLeftMargin(131.7092)
layout:setRightMargin(798.2908)
layout:setTopMargin(223.2110)
layout:setBottomMargin(-258.2110)
Panel_1:addChild(btnFriend)

--Create mainhead
innerCSD = require("views.common.head")
innerProject = innerCSD.create(callBackProvider)
local mainhead = innerProject.root
mainhead.animation = innerProject.animation
mainhead:setName("mainhead")
mainhead:setTag(87)
mainhead:setCascadeColorEnabled(true)
mainhead:setCascadeOpacityEnabled(true)
mainhead:setPosition(207.4197, 22.3210)
layout = ccui.LayoutComponent:bindLayoutComponent(mainhead)
layout:setPositionPercentX(0.1921)
layout:setPositionPercentY(0.1488)
layout:setLeftMargin(207.4197)
layout:setRightMargin(872.5803)
layout:setTopMargin(127.6790)
layout:setBottomMargin(22.3210)
innerProject.animation:setTimeSpeed(1.0000)
mainhead:runAction(innerProject.animation)
Panel_1:addChild(mainhead)

--Create Sprite_5
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
local Sprite_5 = cc.Sprite:createWithSpriteFrameName("head-circle-little.png")
Sprite_5:setName("Sprite_5")
Sprite_5:setTag(93)
Sprite_5:setCascadeColorEnabled(true)
Sprite_5:setCascadeOpacityEnabled(true)
Sprite_5:setPosition(288.0760, -39.1009)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_5)
layout:setPositionPercentX(0.2667)
layout:setPositionPercentY(-0.2607)
layout:setPercentWidth(0.0796)
layout:setPercentHeight(0.6200)
layout:setSize({width = 86.0000, height = 93.0000})
layout:setLeftMargin(245.0760)
layout:setRightMargin(748.9240)
layout:setTopMargin(142.6009)
layout:setBottomMargin(-85.6009)
Sprite_5:setBlendFunc({src = 1, dst = 771})
Panel_1:addChild(Sprite_5)

--Create leaveltxt
local leaveltxt = ccui.Text:create()
leaveltxt:ignoreContentAdaptWithSize(true)
leaveltxt:setTextAreaSize({width = 0, height = 0})
leaveltxt:setFontName("Resource/font/FZY4K.ttf")
leaveltxt:setFontSize(48)
leaveltxt:setString([[1]])
leaveltxt:setTextHorizontalAlignment(1)
leaveltxt:setLayoutComponentEnabled(true)
leaveltxt:setName("leaveltxt")
leaveltxt:setTag(94)
leaveltxt:setCascadeColorEnabled(true)
leaveltxt:setCascadeOpacityEnabled(true)
leaveltxt:setPosition(46.0188, 47.9181)
leaveltxt:setTextColor({r = 103, g = 65, b = 78})
layout = ccui.LayoutComponent:bindLayoutComponent(leaveltxt)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5351)
layout:setPositionPercentY(0.5152)
layout:setPercentWidth(0.2093)
layout:setPercentHeight(0.6237)
layout:setSize({width = 18.0000, height = 58.0000})
layout:setLeftMargin(37.0188)
layout:setRightMargin(30.9812)
layout:setTopMargin(16.0819)
layout:setBottomMargin(18.9181)
Sprite_5:addChild(leaveltxt)

--Create btnGold
local btnGold = ccui.Button:create()
btnGold:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnGold:loadTextureNormal("main-top-gold.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnGold:loadTexturePressed("main-top-gold.png",1)
btnGold:loadTextureDisabled("Default/Button_Disable.png",0)
btnGold:setTitleFontSize(14)
btnGold:setTitleColor({r = 65, g = 65, b = 70})
btnGold:setScale9Enabled(true)
btnGold:setCapInsets({x = 15, y = 11, width = 283, height = 70})
btnGold:setLayoutComponentEnabled(true)
btnGold:setName("btnGold")
btnGold:setTag(97)
btnGold:setCascadeColorEnabled(true)
btnGold:setCascadeOpacityEnabled(true)
btnGold:setPosition(486.2493, 77.5944)
btnGold.UserData = {}
btnGold.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btnGold:addClickEventListener(callBackProvider("main_top.lua", btnGold, "btnGold"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnGold)
layout:setPositionPercentX(0.4502)
layout:setPositionPercentY(0.5173)
layout:setPercentWidth(0.2898)
layout:setPercentHeight(0.6133)
layout:setSize({width = 313.0000, height = 92.0000})
layout:setLeftMargin(329.7493)
layout:setRightMargin(437.2507)
layout:setTopMargin(26.4056)
layout:setBottomMargin(31.5944)
Panel_1:addChild(btnGold)

--Create goldtxt
local goldtxt = ccui.Text:create()
goldtxt:ignoreContentAdaptWithSize(true)
goldtxt:setTextAreaSize({width = 0, height = 0})
goldtxt:setFontName("Resource/font/FZY4K.ttf")
goldtxt:setFontSize(30)
goldtxt:setString([[42,000]])
goldtxt:setTextHorizontalAlignment(1)
goldtxt:enableOutline({r = 255, g = 255, b = 255, a = 255}, 3)
goldtxt:setLayoutComponentEnabled(true)
goldtxt:setName("goldtxt")
goldtxt:setTag(99)
goldtxt:setCascadeColorEnabled(true)
goldtxt:setCascadeOpacityEnabled(true)
goldtxt:setPosition(162.1653, 43.1572)
goldtxt:setTextColor({r = 103, g = 65, b = 78})
layout = ccui.LayoutComponent:bindLayoutComponent(goldtxt)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5181)
layout:setPositionPercentY(0.4691)
layout:setPercentWidth(0.3163)
layout:setPercentHeight(0.4565)
layout:setSize({width = 99.0000, height = 42.0000})
layout:setLeftMargin(112.6653)
layout:setRightMargin(101.3347)
layout:setTopMargin(27.8428)
layout:setBottomMargin(22.1572)
btnGold:addChild(goldtxt)

--Create btnGem
local btnGem = ccui.Button:create()
btnGem:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnGem:loadTextureNormal("main-top-gem.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnGem:loadTexturePressed("main-top-gem.png",1)
btnGem:loadTextureDisabled("Default/Button_Disable.png",0)
btnGem:setTitleFontSize(14)
btnGem:setTitleColor({r = 65, g = 65, b = 70})
btnGem:setScale9Enabled(true)
btnGem:setCapInsets({x = 15, y = 11, width = 284, height = 68})
btnGem:setLayoutComponentEnabled(true)
btnGem:setName("btnGem")
btnGem:setTag(98)
btnGem:setCascadeColorEnabled(true)
btnGem:setCascadeOpacityEnabled(true)
btnGem:setPosition(821.9022, 81.2779)
btnGem.UserData = {}
btnGem.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btnGem:addClickEventListener(callBackProvider("main_top.lua", btnGem, "btnGem"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnGem)
layout:setPositionPercentX(0.7610)
layout:setPositionPercentY(0.5419)
layout:setPercentWidth(0.2907)
layout:setPercentHeight(0.6000)
layout:setSize({width = 314.0000, height = 90.0000})
layout:setLeftMargin(664.9022)
layout:setRightMargin(101.0978)
layout:setTopMargin(23.7221)
layout:setBottomMargin(36.2779)
Panel_1:addChild(btnGem)

--Create gemtxt
local gemtxt = ccui.Text:create()
gemtxt:ignoreContentAdaptWithSize(true)
gemtxt:setTextAreaSize({width = 0, height = 0})
gemtxt:setFontName("Resource/font/FZY4K.ttf")
gemtxt:setFontSize(30)
gemtxt:setString([[250]])
gemtxt:setTextHorizontalAlignment(1)
gemtxt:enableOutline({r = 255, g = 255, b = 255, a = 255}, 3)
gemtxt:setLayoutComponentEnabled(true)
gemtxt:setName("gemtxt")
gemtxt:setTag(100)
gemtxt:setCascadeColorEnabled(true)
gemtxt:setCascadeOpacityEnabled(true)
gemtxt:setPosition(166.9538, 39.3210)
gemtxt:setTextColor({r = 103, g = 65, b = 78})
layout = ccui.LayoutComponent:bindLayoutComponent(gemtxt)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5317)
layout:setPositionPercentY(0.4369)
layout:setPercentWidth(0.1815)
layout:setPercentHeight(0.4667)
layout:setSize({width = 57.0000, height = 42.0000})
layout:setLeftMargin(138.4538)
layout:setRightMargin(118.5462)
layout:setTopMargin(29.6790)
layout:setBottomMargin(18.3210)
btnGem:addChild(gemtxt)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = mainTop
return result;
end

return Result

