--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_3
local Panel_3 = ccui.Layout:create()
Panel_3:ignoreContentAdaptWithSize(false)
Panel_3:setClippingEnabled(false)
Panel_3:setBackGroundColorType(1)
Panel_3:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_3:setBackGroundColorOpacity(0)
Panel_3:setLayoutComponentEnabled(true)
Panel_3:setName("Panel_3")
Panel_3:setTag(129)
Panel_3:setCascadeColorEnabled(true)
Panel_3:setCascadeOpacityEnabled(true)
Panel_3:setAnchorPoint(0.5000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_3)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 1080.0000, height = 150.0000})
layout:setLeftMargin(-540.0000)
layout:setRightMargin(-540.0000)
layout:setTopMargin(-150.0000)
Node:addChild(Panel_3)

--Create btn_1
local btn_1 = ccui.Button:create()
btn_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btn_1:loadTextureNormal("main-btn-single.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btn_1:loadTexturePressed("main-btn-single.png",1)
btn_1:loadTextureDisabled("Default/Button_Disable.png",0)
btn_1:setTitleFontSize(14)
btn_1:setTitleColor({r = 65, g = 65, b = 70})
btn_1:setScale9Enabled(true)
btn_1:setCapInsets({x = 15, y = 11, width = 139, height = 134})
btn_1:setLayoutComponentEnabled(true)
btn_1:setName("btn_1")
btn_1:setTag(130)
btn_1:setCascadeColorEnabled(true)
btn_1:setCascadeOpacityEnabled(true)
btn_1:setPosition(190.9013, 95.8299)
btn_1.UserData = {}
btn_1.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btn_1:addClickEventListener(callBackProvider("main_bm_btn.lua", btn_1, "btn_1"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_1)
layout:setPositionPercentX(0.1768)
layout:setPositionPercentY(0.6389)
layout:setPercentWidth(0.1565)
layout:setPercentHeight(1.0400)
layout:setSize({width = 169.0000, height = 156.0000})
layout:setLeftMargin(106.4013)
layout:setRightMargin(804.5987)
layout:setTopMargin(-23.8299)
layout:setBottomMargin(17.8299)
Panel_3:addChild(btn_1)

--Create btn_2
local btn_2 = ccui.Button:create()
btn_2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btn_2:loadTextureNormal("main-btn-pk.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btn_2:loadTexturePressed("main-btn-pk.png",1)
btn_2:loadTextureDisabled("Default/Button_Disable.png",0)
btn_2:setTitleFontSize(14)
btn_2:setTitleColor({r = 65, g = 65, b = 70})
btn_2:setScale9Enabled(true)
btn_2:setCapInsets({x = 15, y = 11, width = 139, height = 134})
btn_2:setLayoutComponentEnabled(true)
btn_2:setName("btn_2")
btn_2:setTag(131)
btn_2:setCascadeColorEnabled(true)
btn_2:setCascadeOpacityEnabled(true)
btn_2:setPosition(422.7832, 95.5617)
btn_2.UserData = {}
btn_2.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btn_2:addClickEventListener(callBackProvider("main_bm_btn.lua", btn_2, "btn_2"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_2)
layout:setPositionPercentX(0.3915)
layout:setPositionPercentY(0.6371)
layout:setPercentWidth(0.1565)
layout:setPercentHeight(1.0400)
layout:setSize({width = 169.0000, height = 156.0000})
layout:setLeftMargin(338.2832)
layout:setRightMargin(572.7168)
layout:setTopMargin(-23.5617)
layout:setBottomMargin(17.5617)
Panel_3:addChild(btn_2)

--Create btn_3
local btn_3 = ccui.Button:create()
btn_3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btn_3:loadTextureNormal("main-btn-friend.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btn_3:loadTexturePressed("main-btn-friend.png",1)
btn_3:loadTextureDisabled("Default/Button_Disable.png",0)
btn_3:setTitleFontSize(14)
btn_3:setTitleColor({r = 65, g = 65, b = 70})
btn_3:setScale9Enabled(true)
btn_3:setCapInsets({x = 15, y = 11, width = 139, height = 134})
btn_3:setLayoutComponentEnabled(true)
btn_3:setName("btn_3")
btn_3:setTag(132)
btn_3:setCascadeColorEnabled(true)
btn_3:setCascadeOpacityEnabled(true)
btn_3:setPosition(656.3372, 95.7071)
btn_3.UserData = {}
btn_3.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btn_3:addClickEventListener(callBackProvider("main_bm_btn.lua", btn_3, "btn_3"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_3)
layout:setPositionPercentX(0.6077)
layout:setPositionPercentY(0.6380)
layout:setPercentWidth(0.1565)
layout:setPercentHeight(1.0400)
layout:setSize({width = 169.0000, height = 156.0000})
layout:setLeftMargin(571.8372)
layout:setRightMargin(339.1628)
layout:setTopMargin(-23.7071)
layout:setBottomMargin(17.7071)
Panel_3:addChild(btn_3)

--Create btn_4
local btn_4 = ccui.Button:create()
btn_4:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btn_4:loadTextureNormal("main-btn-room.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btn_4:loadTexturePressed("main-btn-room.png",1)
btn_4:loadTextureDisabled("Default/Button_Disable.png",0)
btn_4:setTitleFontSize(14)
btn_4:setTitleColor({r = 65, g = 65, b = 70})
btn_4:setScale9Enabled(true)
btn_4:setCapInsets({x = 15, y = 11, width = 139, height = 134})
btn_4:setLayoutComponentEnabled(true)
btn_4:setName("btn_4")
btn_4:setTag(133)
btn_4:setCascadeColorEnabled(true)
btn_4:setCascadeOpacityEnabled(true)
btn_4:setPosition(887.3391, 95.9750)
btn_4.UserData = {}
btn_4.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btn_4:addClickEventListener(callBackProvider("main_bm_btn.lua", btn_4, "btn_4"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_4)
layout:setPositionPercentX(0.8216)
layout:setPositionPercentY(0.6398)
layout:setPercentWidth(0.1565)
layout:setPercentHeight(1.0400)
layout:setSize({width = 169.0000, height = 156.0000})
layout:setLeftMargin(802.8391)
layout:setRightMargin(108.1609)
layout:setTopMargin(-23.9750)
layout:setBottomMargin(17.9750)
Panel_3:addChild(btn_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

