--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 255, g = 166, b = 195})
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(103)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 1080.0000, height = 150.0000})
layout:setLeftMargin(-540.0000)
layout:setRightMargin(-540.0000)
layout:setTopMargin(-150.0000)
Node:addChild(Panel_1)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("main-bm-line.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(110)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(540.0000, 159.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(1.0600)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2667)
layout:setSize({width = 1080.0000, height = 40.0000})
layout:setTopMargin(-29.0000)
layout:setBottomMargin(139.0000)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Panel_1:addChild(Sprite_1)

--Create Panel_3
local Panel_3 = ccui.Layout:create()
Panel_3:ignoreContentAdaptWithSize(false)
Panel_3:setClippingEnabled(false)
Panel_3:setBackGroundColorType(1)
Panel_3:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_3:setBackGroundColorOpacity(0)
Panel_3:setTouchEnabled(true);
Panel_3:setLayoutComponentEnabled(true)
Panel_3:setName("Panel_3")
Panel_3:setTag(111)
Panel_3:setCascadeColorEnabled(true)
Panel_3:setCascadeOpacityEnabled(true)
Panel_3:setAnchorPoint(0.5000, 0.0000)
Panel_3:setPosition(540.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_3)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 150.0000})
Panel_1:addChild(Panel_3)

--Create btnSingle
local btnSingle = ccui.Button:create()
btnSingle:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnSingle:loadTextureNormal("main-btn-single.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnSingle:loadTexturePressed("main-btn-single.png",1)
btnSingle:loadTextureDisabled("Default/Button_Disable.png",0)
btnSingle:setTitleFontSize(14)
btnSingle:setTitleColor({r = 65, g = 65, b = 70})
btnSingle:setScale9Enabled(true)
btnSingle:setCapInsets({x = 15, y = 11, width = 139, height = 134})
btnSingle:setLayoutComponentEnabled(true)
btnSingle:setName("btnSingle")
btnSingle:setTag(112)
btnSingle:setCascadeColorEnabled(true)
btnSingle:setCascadeOpacityEnabled(true)
btnSingle:setPosition(190.9013, 95.8299)
btnSingle.UserData = {}
btnSingle.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btnSingle:addClickEventListener(callBackProvider("main_bottom.lua", btnSingle, "btnSingle"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnSingle)
layout:setPositionPercentX(0.1768)
layout:setPositionPercentY(0.6389)
layout:setPercentWidth(0.1565)
layout:setPercentHeight(1.0400)
layout:setSize({width = 169.0000, height = 156.0000})
layout:setLeftMargin(106.4013)
layout:setRightMargin(804.5987)
layout:setTopMargin(-23.8299)
layout:setBottomMargin(17.8299)
Panel_3:addChild(btnSingle)

--Create btnPK
local btnPK = ccui.Button:create()
btnPK:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnPK:loadTextureNormal("main-btn-pk.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnPK:loadTexturePressed("main-btn-pk.png",1)
btnPK:loadTextureDisabled("Default/Button_Disable.png",0)
btnPK:setTitleFontSize(14)
btnPK:setTitleColor({r = 65, g = 65, b = 70})
btnPK:setScale9Enabled(true)
btnPK:setCapInsets({x = 15, y = 11, width = 139, height = 134})
btnPK:setLayoutComponentEnabled(true)
btnPK:setName("btnPK")
btnPK:setTag(113)
btnPK:setCascadeColorEnabled(true)
btnPK:setCascadeOpacityEnabled(true)
btnPK:setPosition(422.7832, 95.5617)
btnPK.UserData = {}
btnPK.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btnPK:addClickEventListener(callBackProvider("main_bottom.lua", btnPK, "btnPK"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnPK)
layout:setPositionPercentX(0.3915)
layout:setPositionPercentY(0.6371)
layout:setPercentWidth(0.1565)
layout:setPercentHeight(1.0400)
layout:setSize({width = 169.0000, height = 156.0000})
layout:setLeftMargin(338.2832)
layout:setRightMargin(572.7168)
layout:setTopMargin(-23.5617)
layout:setBottomMargin(17.5617)
Panel_3:addChild(btnPK)

--Create btnAnimal
local btnAnimal = ccui.Button:create()
btnAnimal:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnAnimal:loadTextureNormal("main-btn-friend.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnAnimal:loadTexturePressed("main-btn-friend.png",1)
btnAnimal:loadTextureDisabled("Default/Button_Disable.png",0)
btnAnimal:setTitleFontSize(14)
btnAnimal:setTitleColor({r = 65, g = 65, b = 70})
btnAnimal:setScale9Enabled(true)
btnAnimal:setCapInsets({x = 15, y = 11, width = 139, height = 134})
btnAnimal:setLayoutComponentEnabled(true)
btnAnimal:setName("btnAnimal")
btnAnimal:setTag(114)
btnAnimal:setCascadeColorEnabled(true)
btnAnimal:setCascadeOpacityEnabled(true)
btnAnimal:setPosition(656.3372, 95.7071)
btnAnimal.UserData = {}
btnAnimal.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btnAnimal:addClickEventListener(callBackProvider("main_bottom.lua", btnAnimal, "btnAnimal"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnAnimal)
layout:setPositionPercentX(0.6077)
layout:setPositionPercentY(0.6380)
layout:setPercentWidth(0.1565)
layout:setPercentHeight(1.0400)
layout:setSize({width = 169.0000, height = 156.0000})
layout:setLeftMargin(571.8372)
layout:setRightMargin(339.1628)
layout:setTopMargin(-23.7071)
layout:setBottomMargin(17.7071)
Panel_3:addChild(btnAnimal)

--Create btnRoom
local btnRoom = ccui.Button:create()
btnRoom:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnRoom:loadTextureNormal("main-btn-room.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/B-common.plist")
btnRoom:loadTexturePressed("main-btn-room.png",1)
btnRoom:loadTextureDisabled("Default/Button_Disable.png",0)
btnRoom:setTitleFontSize(14)
btnRoom:setTitleColor({r = 65, g = 65, b = 70})
btnRoom:setScale9Enabled(true)
btnRoom:setCapInsets({x = 15, y = 11, width = 139, height = 134})
btnRoom:setLayoutComponentEnabled(true)
btnRoom:setName("btnRoom")
btnRoom:setTag(115)
btnRoom:setCascadeColorEnabled(true)
btnRoom:setCascadeOpacityEnabled(true)
btnRoom:setPosition(887.3391, 95.9750)
btnRoom.UserData = {}
btnRoom.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btnRoom:addClickEventListener(callBackProvider("main_bottom.lua", btnRoom, "btnRoom"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnRoom)
layout:setPositionPercentX(0.8216)
layout:setPositionPercentY(0.6398)
layout:setPercentWidth(0.1565)
layout:setPercentHeight(1.0400)
layout:setSize({width = 169.0000, height = 156.0000})
layout:setLeftMargin(802.8391)
layout:setRightMargin(108.1609)
layout:setTopMargin(-23.9750)
layout:setBottomMargin(17.9750)
Panel_3:addChild(btnRoom)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

