--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(106)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setPosition(-371.2239, -207.8034)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setSize({width = 750.0000, height = 200.0000})
layout:setLeftMargin(-371.2239)
layout:setRightMargin(-378.7761)
layout:setTopMargin(7.8034)
layout:setBottomMargin(-207.8034)
Node:addChild(Panel_1)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-home.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("btn-main-noads.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(107)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(-342.9792, -56.4887)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setSize({width = 46.0000, height = 45.0000})
layout:setLeftMargin(-365.9792)
layout:setRightMargin(319.9792)
layout:setTopMargin(33.9887)
layout:setBottomMargin(-78.9887)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Node:addChild(Sprite_1)

--Create Sprite_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-home.plist")
local Sprite_2 = cc.Sprite:createWithSpriteFrameName("btn-main-start-board-n.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(108)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(36.3220, -94.8196)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setSize({width = 680.0000, height = 188.0000})
layout:setLeftMargin(-303.6780)
layout:setRightMargin(-376.3220)
layout:setTopMargin(0.8196)
layout:setBottomMargin(-188.8196)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Node:addChild(Sprite_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

