--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 750.0000, height = 1334.0000})

--Create countdown
local countdown = ccui.Text:create()
countdown:ignoreContentAdaptWithSize(true)
countdown:setTextAreaSize({width = 0, height = 0})
countdown:setFontName("Resource/fonts/OverlapExt.ttf")
countdown:setFontSize(72)
countdown:setString([[0]])
countdown:enableOutline({r = 255, g = 255, b = 255, a = 255}, 2)
countdown:setLayoutComponentEnabled(true)
countdown:setName("countdown")
countdown:setTag(280)
countdown:setCascadeColorEnabled(true)
countdown:setCascadeOpacityEnabled(true)
countdown:setAnchorPoint(0.0000, 0.5000)
countdown:setPosition(60.6599, 1264.3390)
countdown:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(countdown)
layout:setPositionPercentX(0.0809)
layout:setPositionPercentY(0.9478)
layout:setPercentWidth(0.0453)
layout:setPercentHeight(0.0630)
layout:setSize({width = 36.0000, height = 88.0000})
layout:setLeftMargin(60.6599)
layout:setRightMargin(655.3401)
layout:setTopMargin(27.6608)
layout:setBottomMargin(1222.3390)
Layer:addChild(countdown)

--Create score
local score = ccui.Text:create()
score:ignoreContentAdaptWithSize(true)
score:setTextAreaSize({width = 0, height = 0})
score:setFontSize(72)
score:setString([[0]])
score:setLayoutComponentEnabled(true)
score:setName("score")
score:setTag(39)
score:setCascadeColorEnabled(true)
score:setCascadeOpacityEnabled(true)
score:setPosition(572.4724, 1240.5780)
layout = ccui.LayoutComponent:bindLayoutComponent(score)
layout:setPositionPercentX(0.7633)
layout:setPositionPercentY(0.9300)
layout:setPercentWidth(0.0547)
layout:setPercentHeight(0.0607)
layout:setSize({width = 41.0000, height = 81.0000})
layout:setLeftMargin(551.9724)
layout:setRightMargin(157.0276)
layout:setTopMargin(52.9221)
layout:setBottomMargin(1200.0780)
Layer:addChild(score)

--Create btn_pause
local btn_pause = ccui.Button:create()
btn_pause:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
btn_pause:loadTextureNormal("btn-game-pause.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
btn_pause:loadTexturePressed("btn-game-pause.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
btn_pause:loadTextureDisabled("btn-game-pause.png",1)
btn_pause:setTitleFontSize(14)
btn_pause:setTitleColor({r = 65, g = 65, b = 70})
btn_pause:setScale9Enabled(true)
btn_pause:setCapInsets({x = 15, y = 11, width = 45, height = 61})
btn_pause:setLayoutComponentEnabled(true)
btn_pause:setName("btn_pause")
btn_pause:setTag(43)
btn_pause:setCascadeColorEnabled(true)
btn_pause:setCascadeOpacityEnabled(true)
btn_pause:setPosition(645.4457, 1267.2170)
if callBackProvider~=nil then
      btn_pause:addClickEventListener(callBackProvider("game_hud.lua", btn_pause, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_pause)
layout:setPositionPercentX(0.8606)
layout:setPositionPercentY(0.9499)
layout:setPercentWidth(0.1000)
layout:setPercentHeight(0.0622)
layout:setSize({width = 75.0000, height = 83.0000})
layout:setLeftMargin(607.9457)
layout:setRightMargin(67.0543)
layout:setTopMargin(25.2834)
layout:setBottomMargin(1225.7170)
Layer:addChild(btn_pause)

--Create panel_skill
local panel_skill = ccui.Layout:create()
panel_skill:ignoreContentAdaptWithSize(false)
panel_skill:setClippingEnabled(false)
panel_skill:setBackGroundColorType(1)
panel_skill:setBackGroundColor({r = 150, g = 200, b = 255})
panel_skill:setBackGroundColorOpacity(0)
panel_skill:setLayoutComponentEnabled(true)
panel_skill:setName("panel_skill")
panel_skill:setTag(117)
panel_skill:setCascadeColorEnabled(true)
panel_skill:setCascadeOpacityEnabled(true)
panel_skill:setAnchorPoint(0.5000, 0.0000)
panel_skill:setPosition(375.0000, 497.1239)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_skill)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3727)
layout:setPercentWidth(0.4000)
layout:setPercentHeight(0.0600)
layout:setSize({width = 300.0000, height = 80.0000})
layout:setLeftMargin(225.0000)
layout:setRightMargin(225.0000)
layout:setTopMargin(756.8761)
layout:setBottomMargin(497.1239)
Layer:addChild(panel_skill)

--Create Panel_2
local Panel_2 = ccui.Layout:create()
Panel_2:ignoreContentAdaptWithSize(false)
Panel_2:setClippingEnabled(false)
Panel_2:setBackGroundColorType(1)
Panel_2:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_2:setBackGroundColorOpacity(0)
Panel_2:setLayoutComponentEnabled(true)
Panel_2:setName("Panel_2")
Panel_2:setTag(110)
Panel_2:setCascadeColorEnabled(true)
Panel_2:setCascadeOpacityEnabled(true)
Panel_2:setAnchorPoint(0.5000, 0.0000)
Panel_2:setPosition(354.1500, 1234.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.4722)
layout:setPositionPercentY(0.9250)
layout:setPercentWidth(0.5067)
layout:setPercentHeight(0.0750)
layout:setSize({width = 380.0000, height = 100.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(164.1500)
layout:setRightMargin(205.8500)
layout:setBottomMargin(1234.0000)
Layer:addChild(Panel_2)

--Create star1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local star1 = cc.Sprite:createWithSpriteFrameName("sp-result-star.png")
star1:setName("star1")
star1:setTag(111)
star1:setCascadeColorEnabled(true)
star1:setCascadeOpacityEnabled(true)
star1:setPosition(95.0000, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(star1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.2500)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1368)
layout:setPercentHeight(0.5200)
layout:setSize({width = 52.0000, height = 52.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(69.0000)
layout:setRightMargin(259.0000)
layout:setTopMargin(24.0000)
layout:setBottomMargin(24.0000)
star1:setBlendFunc({src = 1, dst = 771})
Panel_2:addChild(star1)

--Create star2
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local star2 = cc.Sprite:createWithSpriteFrameName("sp-result-star.png")
star2:setName("star2")
star2:setTag(112)
star2:setCascadeColorEnabled(true)
star2:setCascadeOpacityEnabled(true)
star2:setPosition(190.0000, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(star2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1368)
layout:setPercentHeight(0.5200)
layout:setSize({width = 52.0000, height = 52.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(164.0000)
layout:setRightMargin(164.0000)
layout:setTopMargin(24.0000)
layout:setBottomMargin(24.0000)
star2:setBlendFunc({src = 1, dst = 771})
Panel_2:addChild(star2)

--Create star3
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local star3 = cc.Sprite:createWithSpriteFrameName("sp-result-star.png")
star3:setName("star3")
star3:setTag(113)
star3:setCascadeColorEnabled(true)
star3:setCascadeOpacityEnabled(true)
star3:setPosition(285.0000, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(star3)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.7500)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1368)
layout:setPercentHeight(0.5200)
layout:setSize({width = 52.0000, height = 52.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(259.0000)
layout:setRightMargin(69.0000)
layout:setTopMargin(24.0000)
layout:setBottomMargin(24.0000)
star3:setBlendFunc({src = 1, dst = 771})
Panel_2:addChild(star3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

